<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.353">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="HeiYee Lau">

<title>HW7</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="HW7_files/libs/clipboard/clipboard.min.js"></script>
<script src="HW7_files/libs/quarto-html/quarto.js"></script>
<script src="HW7_files/libs/quarto-html/popper.min.js"></script>
<script src="HW7_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="HW7_files/libs/quarto-html/anchor.min.js"></script>
<link href="HW7_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="HW7_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="HW7_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="HW7_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="HW7_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">HW7</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>HeiYee Lau </p>
          </div>
  </div>
    
  
    
  </div>
  

</header>

<p>Consider the data set snails.csv. We are interested in modeling counts of the snail species Gaenig. Do a random 80-20 train-test split of this data, using set.seed(123457), fitting suitable models to the train data and evaluating the fit on the test data.</p>
<p>In each case, compute and discuss</p>
<p>model coefficients</p>
<p>dispersion parameter</p>
<p>model adequacy (chi-squared test, deviance residuals)</p>
<p>information criteria</p>
<p>in-sample MAD on the training data</p>
<p>out-of-sample MAD on the test data.</p>
<p>Based on (i) - (vi), do you have a preference for one of the models (a), (b), or (c)? In your selected model, which predictors are useful for explaining and predicting Gaening counts?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readr)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(Metrics)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(MASS)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>snails <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"snails.csv"</span>, <span class="at">header =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>snails<span class="sc">$</span>Aspect[snails<span class="sc">$</span>Aspect<span class="sc">==</span><span class="dv">6</span>]<span class="ot">=</span><span class="dv">5</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>snails<span class="sc">$</span>Aspect[snails<span class="sc">$</span>Aspect<span class="sc">==</span><span class="dv">2</span>]<span class="ot">=</span><span class="dv">1</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>snails<span class="sc">$</span>Aspect <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(snails<span class="sc">$</span>Aspect)</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>snails<span class="sc">$</span>Soil <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(snails<span class="sc">$</span>Soil)</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>snails<span class="sc">$</span>CC <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(snails<span class="sc">$</span>CC)</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>snails<span class="sc">$</span>LC <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(snails<span class="sc">$</span>LC)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>cat.id <span class="ot">&lt;-</span> <span class="fu">which</span>(<span class="fu">colnames</span>(snails) <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"Aspect"</span>,<span class="st">"Soil"</span>,<span class="st">"CC"</span>,<span class="st">"LC"</span>))</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>snails[,cat.id] <span class="ot">&lt;-</span> <span class="fu">lapply</span>(snails[,cat.id],as.factor)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>Asp1 <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(snails<span class="sc">$</span>Aspect <span class="sc">==</span> <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">0</span>)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>Asp5 <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(snails<span class="sc">$</span>Aspect <span class="sc">==</span> <span class="dv">5</span>, <span class="dv">1</span>, <span class="dv">0</span>)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>Asp7 <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(snails<span class="sc">$</span>Aspect <span class="sc">==</span> <span class="dv">7</span>, <span class="dv">1</span>, <span class="dv">0</span>)</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>Asp8 <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(snails<span class="sc">$</span>Aspect <span class="sc">==</span> <span class="dv">8</span>, <span class="dv">1</span>, <span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123457</span>)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>train.prop <span class="ot">&lt;-</span> <span class="fl">0.80</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>trnset <span class="ot">&lt;-</span> <span class="fu">sort</span>(<span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(snails), <span class="fu">ceiling</span>(<span class="fu">nrow</span>(snails)<span class="sc">*</span>train.prop)))</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>train.set <span class="ot">&lt;-</span> snails[trnset, ]</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>test.set <span class="ot">&lt;-</span> snails[<span class="sc">-</span>trnset, ]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Fit and assess the Poisson loglinear model to Gaenig counts using the train data.</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>gaenig.pf <span class="ot">&lt;-</span> <span class="fu">glm</span>(Gaenig<span class="sc">~</span>Elevation<span class="sc">+</span>Slope<span class="sc">+</span>Aspect<span class="sc">+</span>Soil<span class="sc">+</span>CC<span class="sc">+</span>CO<span class="sc">+</span>LC<span class="sc">+</span>PA.sp<span class="sc">+</span>PA.other, <span class="at">family=</span><span class="st">'poisson'</span>, <span class="at">data=</span>train.set)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(gaenig.pf)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = Gaenig ~ Elevation + Slope + Aspect + Soil + CC + 
    CO + LC + PA.sp + PA.other, family = "poisson", data = train.set)

Coefficients:
             Estimate Std. Error z value Pr(&gt;|z|)   
(Intercept)  0.433161   3.417118   0.127  0.89913   
Elevation    0.002851   0.008574   0.333  0.73947   
Slope       -0.007304   0.011597  -0.630  0.52881   
Aspect5     -0.373324   0.358521  -1.041  0.29774   
Aspect7     -0.504974   0.303390  -1.664  0.09602 . 
Aspect8     -0.355122   0.250721  -1.416  0.15666   
Soil4       -0.946090   0.322681  -2.932  0.00337 **
Soil6       -0.723771   0.610738  -1.185  0.23599   
CC2         -0.354286   0.316442  -1.120  0.26289   
CC3          0.025263   0.252329   0.100  0.92025   
CO          -0.115196   0.064217  -1.794  0.07284 . 
LC2          0.075579   0.304032   0.249  0.80368   
LC3         -0.241558   0.318611  -0.758  0.44836   
LC4          0.054934   0.332660   0.165  0.86884   
LC5         -0.037878   0.481135  -0.079  0.93725   
PA.sp        0.009332   0.016399   0.569  0.56931   
PA.other    -0.011724   0.005824  -2.013  0.04412 * 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for poisson family taken to be 1)

    Null deviance: 205.68  on 120  degrees of freedom
Residual deviance: 174.65  on 104  degrees of freedom
AIC: 378.72

Number of Fisher Scoring iterations: 6</code></pre>
</div>
</div>
<p>For the Poisson loglinear model to Gaenig counts using the train data, the family is specified as “poisson” and the dataset we used is the train.set on which the model was trained. The model provided the estimates for the coefficients of the model. Most of the variable have the negative correlation with Gaenig. For each one-unit increase in ‘Elevation’, the log of the count is expected to increase by 0.002851 and for each one-unit decrease in ‘Slope’, the log of the count is expected to decrease by 0.007304 The coefficient of Aspect 5,7 and 8 indicate how the log count change when Aspect is 5,7 or 8 compared to a reference category. Same with the variables of Soil, CC, PA.sp and PA.other. The null deviance is 205.68 and the residual deviance is 174.65.</p>
<p>The reduction of deviance indicates that the model with the selected predictor variables provide a better fit to the data compared to a null model with no predictors. Since the residual deviance is smaller than the null deviance suggests that the Poisson model is doing a good job for explaining the observed data, as it reduces the deviance substantially be incorporating the predictor variables.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># null model</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>gaenig.npf <span class="ot">&lt;-</span> <span class="fu">glm</span>(Gaenig<span class="sc">~</span><span class="dv">1</span>, </span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>                 <span class="at">family=</span><span class="st">'poisson'</span>, <span class="at">data=</span>train.set)</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(gaenig.npf)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = Gaenig ~ 1, family = "poisson", data = train.set)

Coefficients:
            Estimate Std. Error z value Pr(&gt;|z|)
(Intercept)  0.13868    0.08482   1.635    0.102

(Dispersion parameter for poisson family taken to be 1)

    Null deviance: 205.68  on 120  degrees of freedom
Residual deviance: 205.68  on 120  degrees of freedom
AIC: 377.75

Number of Fisher Scoring iterations: 5</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co">#dispersion parameter</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>(disp.est <span class="ot">&lt;-</span> gaenig.pf<span class="sc">$</span>deviance<span class="sc">/</span>gaenig.pf<span class="sc">$</span>df.residual)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.679366</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co">#dispersion parameter for null</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>(disp.est <span class="ot">&lt;-</span> gaenig.npf<span class="sc">$</span>deviance<span class="sc">/</span>gaenig.npf<span class="sc">$</span>df.residual)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.714006</code></pre>
</div>
</div>
<p>The dispersion parameter in a Poisson regression model is a measure of how well the model accounts for the variability in the data. It quantifies the relationship between the observed variance and the expected variance under the model. In the case, the dispersion parameter value is 1.679, suggests that the model has overdispersion, it occurred when the observed variance in the data is greater than what is expected based on a Poisson distribution.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co">#chi-square test</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>(gaenig.pf, <span class="fu">cbind</span>(<span class="at">deviance =</span> deviance, <span class="at">df =</span> df.residual,</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">p =</span> <span class="fu">pchisq</span>(deviance, df.residual, <span class="at">lower.tail=</span><span class="cn">FALSE</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     deviance  df            p
[1,]  174.654 104 1.771981e-05</code></pre>
</div>
</div>
<p>Null Hypothesis: The data prefer full fitted model</p>
<p>Alternative Hypothesis: The data does not prefer the full fitted model</p>
<p>In the Chi-squared test, the p-value is 1.771981e-05, is smaller than the significant level (0.05), shows that the data rejects H0 (null model) and not prefer the full fitted model ,which suggests that the Poisson regression model is not significantly improves the fit over the null model. We can compare the deviance value (177.9315) with other model to see if it is the better fit model among others.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>(gaenig.pf, <span class="fu">cbind</span>(<span class="at">deviance =</span> null.deviance<span class="sc">-</span>deviance, </span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>                      <span class="at">df =</span> df.null<span class="sc">-</span>df.residual,</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>                      <span class="at">p =</span> <span class="fu">pchisq</span>(null.deviance<span class="sc">-</span>deviance, </span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>                      df.null<span class="sc">-</span>df.residual, </span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>                      <span class="at">lower.tail=</span><span class="cn">FALSE</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     deviance df          p
[1,] 31.02666 16 0.01335116</code></pre>
</div>
</div>
<p>We would like to see whether all the predictors aken together are useful for explaining log count over and above the intercept along. We have compared with the null model.</p>
<p>The extra deviance is 31.0267 and extra degree freedom is 16. The p-value is 0.01335116 which is smaller than the significant level (0.05), indicate we can reject H0 and prefers the full fitted model. But if we adjust the significant level to 0.01, we can accept the null hypthoesis and prefer the null model.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co">#deviance residuals</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>gaenig.pf.res <span class="ot">&lt;-</span> <span class="fu">resid</span>(gaenig.pf, <span class="at">type =</span> <span class="st">"deviance"</span>) </span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(gaenig.pf.res)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
-1.8901 -1.2320 -0.5209 -0.2642  0.5024  3.1467 </code></pre>
</div>
</div>
<p>From the deviance residual, we can see that the model has a mix of both overpredictions and underpredictions. The mean residual being negative (-0.2642), which suggests that the model is slightly underpredicts the count for your data. Since the maximum value of 3.1467 that has a wide gap between the 3rd quantile, it suggests that there might be outliers or extreme values among the residual and indicate the model’s predictions are particularly poor.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Information criteria</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="fu">AIC</span>(gaenig.pf, gaenig.npf)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>           df      AIC
gaenig.pf  17 378.7204
gaenig.npf  1 377.7470</code></pre>
</div>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">BIC</span>(gaenig.pf, gaenig.npf)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>           df      BIC
gaenig.pf  17 426.2488
gaenig.npf  1 380.5428</code></pre>
</div>
</div>
<p>AIC is a measure of the trade-off between model fit and model complexity. Lower AIC values indicate a better balance between explaining the data and avoiding overfitting. In the null model, we can see that the AIC value for full fitted model is approximately 378.7204 and for the null model is 377.7470. It shows that null model is the better fit model because it has the smaller AIC.</p>
<p>BIC is similar to AIC but places a stronger penalty on model complexity. The BIC value in this model is 426.2488 and for null model is 380.5428, which show the same result with AIC that null model is the better model since the smaller BIC.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co">#in-sample mad full fitted model</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>in_sample_mad_poisson <span class="ot">&lt;-</span> <span class="fu">mean</span>(<span class="fu">abs</span>(train.set<span class="sc">$</span>Gaenig <span class="sc">-</span> <span class="fu">predict</span>(gaenig.pf, <span class="at">newdata=</span>train.set, <span class="at">type =</span> <span class="st">"response"</span>)))</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">'In-sample MAD: '</span>, in_sample_mad_poisson)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>In-sample MAD:  0.9860363</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co">#out-sample mad on full fitted model</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>out_sample_mad_poisson <span class="ot">&lt;-</span> <span class="fu">mean</span>(<span class="fu">abs</span>(test.set<span class="sc">$</span>Gaenig <span class="sc">-</span> <span class="fu">predict</span>(gaenig.pf, <span class="at">newdata =</span> test.set, <span class="at">type =</span> <span class="st">"response"</span>)))</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">'Out-sample MAD: '</span>, out_sample_mad_poisson)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Out-sample MAD:  1.037381</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co">#in-sample mad on null model</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>in_sample_mad_poisson_null <span class="ot">&lt;-</span> <span class="fu">mean</span>(<span class="fu">abs</span>(train.set<span class="sc">$</span>Gaenig <span class="sc">-</span> <span class="fu">predict</span>(gaenig.npf, <span class="at">newdata=</span>train.set, <span class="at">type =</span> <span class="st">"response"</span>)))</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">'In-sample MAD for null model: '</span>, in_sample_mad_poisson)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>In-sample MAD for null model:  0.9860363</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co">#out-sample mad on null model</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>out_sample_mad_poisson_null <span class="ot">&lt;-</span> <span class="fu">mean</span>(<span class="fu">abs</span>(test.set<span class="sc">$</span>Gaenig <span class="sc">-</span> <span class="fu">predict</span>(gaenig.npf, <span class="at">newdata =</span> test.set, <span class="at">type =</span> <span class="st">"response"</span>)))</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">'Out-sample MAD for null model: '</span>, out_sample_mad_poisson)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Out-sample MAD for null model:  1.037381</code></pre>
</div>
</div>
<p>The in-sample MAD is approximately 0.9860363 indicates that on average, the model’s predictions are off by about 0.9860363 counts compared to the actual observed counts in the training data.The out-sample MAD of approximately 1.037381 indicates that on average, the model predictions are off by about 1.037381 counts compared to the actual observed counts in the testing data.</p>
<p>And the in-sample MAD is same with the out-sample MAD.</p>
<p><strong>Fit and assess the quasi-Poisson loglinear model to Gaenig counts using the train data.</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>gaenig.qpf <span class="ot">&lt;-</span> <span class="fu">glm</span>(Gaenig<span class="sc">~</span>Elevation<span class="sc">+</span>Slope<span class="sc">+</span>Aspect<span class="sc">+</span>Soil<span class="sc">+</span>CC<span class="sc">+</span>CO<span class="sc">+</span>LC<span class="sc">+</span>PA.sp<span class="sc">+</span>PA.other,</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a> <span class="at">family=</span>quasipoisson,<span class="at">data=</span>train.set)</span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(gaenig.qpf)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = Gaenig ~ Elevation + Slope + Aspect + Soil + CC + 
    CO + LC + PA.sp + PA.other, family = quasipoisson, data = train.set)

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)  
(Intercept)  0.433161   4.416055   0.098   0.9221  
Elevation    0.002851   0.011080   0.257   0.7974  
Slope       -0.007304   0.014988  -0.487   0.6270  
Aspect5     -0.373324   0.463328  -0.806   0.4222  
Aspect7     -0.504974   0.392081  -1.288   0.2006  
Aspect8     -0.355122   0.324015  -1.096   0.2756  
Soil4       -0.946090   0.417012  -2.269   0.0253 *
Soil6       -0.723771   0.789277  -0.917   0.3613  
CC2         -0.354286   0.408948  -0.866   0.3883  
CC3          0.025263   0.326093   0.077   0.9384  
CO          -0.115196   0.082990  -1.388   0.1681  
LC2          0.075579   0.392911   0.192   0.8478  
LC3         -0.241558   0.411752  -0.587   0.5587  
LC4          0.054934   0.429908   0.128   0.8986  
LC5         -0.037878   0.621787  -0.061   0.9515  
PA.sp        0.009332   0.021193   0.440   0.6606  
PA.other    -0.011724   0.007527  -1.558   0.1224  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for quasipoisson family taken to be 1.670125)

    Null deviance: 205.68  on 120  degrees of freedom
Residual deviance: 174.65  on 104  degrees of freedom
AIC: NA

Number of Fisher Scoring iterations: 6</code></pre>
</div>
</div>
<p>For the model coefficient, the intercept is approximately 0.433161. In one-unit increase in Elevation results in an expected increase of approximately 0.002851 in the log count of Gaenig. However, it is not statistically significant at conventional significant at conventional significant levels (p-value&gt;0.05). In one-unit increase in Slope results in an expected decrease of approximately 0.007304 in the log count of Gaenig. The coefficient represents the effect of Aspect 5,7 and 8 on the log count of Gaenig compared to the reference category. Same with Soil, cc, LC, PA.sp and PA.other.The null deviance is 205.68 and the residual deviance is 174.65. The reduction in deviance from the null deviance to the residual deviance indicates that the model is providing a better fit than the null model. Depend on the p-value, Soil4 is significant to the full fit model since the p-value is smaller than the significant level (0.05).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>gaenig.nqpf <span class="ot">&lt;-</span> <span class="fu">glm</span>(Gaenig<span class="sc">~</span><span class="dv">1</span>, <span class="at">family=</span>quasipoisson,<span class="at">data=</span>train.set)</span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(gaenig.nqpf)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = Gaenig ~ 1, family = quasipoisson, data = train.set)

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)
(Intercept)   0.1387     0.1103   1.257    0.211

(Dispersion parameter for quasipoisson family taken to be 1.69264)

    Null deviance: 205.68  on 120  degrees of freedom
Residual deviance: 205.68  on 120  degrees of freedom
AIC: NA

Number of Fisher Scoring iterations: 5</code></pre>
</div>
</div>
<p>For the null model, the estimate intercept is 0.1387 and the deviance is 205.68 on 120 degrees of freedom. The p-value of intercept is 0.211 which is larger than the significant level (0.05) and suggests that it is not significant.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="co">#dispersion parameter</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>(disp.est <span class="ot">&lt;-</span> gaenig.qpf<span class="sc">$</span>deviance<span class="sc">/</span>gaenig.qpf<span class="sc">$</span>df.residual)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.679366</code></pre>
</div>
</div>
<p>The dispersion parameter of 1.679366 suggests that the variance in the data is larger than what would be expected under a typical quasi-Poisson loglinear model. this indicates overdispersion in the data.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="co">#check the adequate (chi-square test)</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>(gaenig.qpf, <span class="fu">cbind</span>(<span class="at">deviance =</span> deviance, <span class="at">df =</span> df.residual,</span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">p =</span> <span class="fu">pchisq</span>(deviance, df.residual, <span class="at">lower.tail=</span><span class="cn">FALSE</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     deviance  df            p
[1,]  174.654 104 1.771981e-05</code></pre>
</div>
</div>
<p>H0: Data prefer full fitted model</p>
<p>H1: Data does not prefer the full fitted model</p>
<p>In the Chi-squared test, the p-value is 1.866122e-06, is smaller than the significant level (0.05), shows that the data rejects H0 (null model) and not prefer the full fitted model (model under H1) ,which suggests that the Quasi-Poisson loglinear model is not a good fit for the data, and there may be a better model that fits the data more effectively. We can compare the deviance value (205.6807) with other model to see if it is the better fit model among others.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="co">#deviance residuals</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>gaenig.qpf.res <span class="ot">&lt;-</span> <span class="fu">resid</span>(gaenig.qpf, <span class="at">type =</span> <span class="st">"deviance"</span>) </span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(gaenig.qpf.res)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
-1.8901 -1.2320 -0.5209 -0.2642  0.5024  3.1467 </code></pre>
</div>
</div>
<p>The minimum deviance residual is approximately -1.8901. This suggests that there are observations in the dataset for which the actual counts are lower than what the model predicts.The 1st quartile of the deviance residuals is approximately -1.2320. This indicates that 25% of the residuals fall below this value. The mean (average) deviance residual is approximately -0.2642. On average, the actual counts deviate by about -0.2642 from the model’s predictions.The third quartile (75th percentile) of the deviance residuals is approximately 0.5024. This indicates that 75% of the residuals fall below this value.The maximum deviance residual is approximately 3.1467. This is the largest positive deviation between the observed counts and the model’s predictions. It suggests that there are data points for which the actual counts are much higher than what the model predicts. There is variability in how the model’s predictions match the observed data. The model tends to overestimate counts on average, as indicated by the negative mean residual.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Information criteria</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a><span class="fu">AIC</span>(gaenig.qpf,gaenig.nqpf )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>            df AIC
gaenig.qpf  18  NA
gaenig.nqpf  2  NA</code></pre>
</div>
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">BIC</span>(gaenig.qpf, gaenig.nqpf)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>            df BIC
gaenig.qpf  18  NA
gaenig.nqpf  2  NA</code></pre>
</div>
</div>
<p>AIC and BIC for full fitted model and null model are marked as ‘NA’ which typically occurs when the model’s likelihood or deviance is not calculable due to specific circumstances, such as convergence isses or other factors affecting the model’s estimation.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="co">#in-sample mad on ful fitte model</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>in_sample_mad_poisson_qpf <span class="ot">&lt;-</span> <span class="fu">mean</span>(<span class="fu">abs</span>(train.set<span class="sc">$</span>Gaenig <span class="sc">-</span> <span class="fu">predict</span>(gaenig.qpf, <span class="at">type =</span> <span class="st">"response"</span>)))</span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">'In-sample MAD: '</span>, in_sample_mad_poisson_qpf)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>In-sample MAD:  0.9860363</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="co">#out-sample mad on full fitted model</span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>out_sample_mad_poisson_qpf <span class="ot">&lt;-</span> <span class="fu">mean</span>(<span class="fu">abs</span>(test.set<span class="sc">$</span>Gaenig <span class="sc">-</span> <span class="fu">predict</span>(gaenig.qpf, <span class="at">newdata =</span> test.set, <span class="at">type =</span> <span class="st">"response"</span>)))</span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">'Out-sample MAD: '</span>, out_sample_mad_poisson_qpf)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Out-sample MAD:  1.037381</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="co">#in-sample mad on null data</span></span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>in_sample_mad_poisson_nqpf <span class="ot">&lt;-</span> <span class="fu">mean</span>(<span class="fu">abs</span>(train.set<span class="sc">$</span>Gaenig <span class="sc">-</span> <span class="fu">predict</span>(gaenig.nqpf, <span class="at">type =</span> <span class="st">"response"</span>)))</span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">'In-sample MAD: '</span>, in_sample_mad_poisson_nqpf)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>In-sample MAD:  1.080117</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="co">#out-sample mad on null data</span></span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a>out_sample_mad_poisson_nqpf <span class="ot">&lt;-</span> <span class="fu">mean</span>(<span class="fu">abs</span>(test.set<span class="sc">$</span>Gaenig <span class="sc">-</span> <span class="fu">predict</span>(gaenig.nqpf, <span class="at">newdata =</span> test.set, <span class="at">type =</span> <span class="st">"response"</span>)))</span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">'Out-sample MAD: '</span>, out_sample_mad_poisson_nqpf)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Out-sample MAD:  0.9126722</code></pre>
</div>
</div>
<p>For the full fitted model, the in-sample MAD is approximately 0.9860363 and the out-of-sample MAD is approximately 1.037381. The MAD values suggests that your model might be too complex or overfitting the training data. It occurs when a model captures noise or random fluctuations in the training data, making it perform well on the training data but poorly on new, unseen data.</p>
<p>For the null model, the in-sample MAD is approximately 1.080117 and the out-of-sample MAD is approximately 0.9126722.It implies that your model may not have learned the underlying patterns in the training data effectively and is not generalizing well to new data.</p>
<p><strong>Fit and assess the negative binomial loglinear model to Gaenig counts using the train data.</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(MASS)</span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a>gaenig.nbn <span class="ot">&lt;-</span> <span class="fu">glm.nb</span>(Gaenig<span class="sc">~</span><span class="dv">1</span>, <span class="at">data =</span> train.set)</span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(gaenig.nbn)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm.nb(formula = Gaenig ~ 1, data = train.set, init.theta = 1.515637598, 
    link = log)

Coefficients:
            Estimate Std. Error z value Pr(&gt;|z|)
(Intercept)   0.1387     0.1125   1.233    0.218

(Dispersion parameter for Negative Binomial(1.5156) family taken to be 1)

    Null deviance: 129.13  on 120  degrees of freedom
Residual deviance: 129.13  on 120  degrees of freedom
AIC: 361.63

Number of Fisher Scoring iterations: 1

              Theta:  1.516 
          Std. Err.:  0.546 

 2 x log-likelihood:  -357.628 </code></pre>
</div>
</div>
<p>We have made a negative regression with only an intercept term. The coefficient for the intercept is 0.1387, but it is not statistically significant because the p-value is 0.218, which is smaller than the significant level (0.05), means that there is not enough evidence to reject the null hypothesis and the intercept is not statistically significant in the model. The dispersion parameter is estimated to be 1.5156. The model’s deviance is 129.13 and the residual deviance is the same. The AIC for this model is 361.63</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a>gaenig.nbf <span class="ot">&lt;-</span> <span class="fu">glm.nb</span>(Gaenig<span class="sc">~</span>Elevation<span class="sc">+</span>Slope<span class="sc">+</span>Aspect<span class="sc">+</span>Soil<span class="sc">+</span>CC<span class="sc">+</span>CO<span class="sc">+</span>LC<span class="sc">+</span>PA.sp<span class="sc">+</span>PA.other, <span class="at">data=</span>train.set)</span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(gaenig.nbf)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm.nb(formula = Gaenig ~ Elevation + Slope + Aspect + Soil + 
    CC + CO + LC + PA.sp + PA.other, data = train.set, init.theta = 2.871689284, 
    link = log)

Coefficients:
             Estimate Std. Error z value Pr(&gt;|z|)  
(Intercept) -0.161328   4.102093  -0.039   0.9686  
Elevation    0.004123   0.010317   0.400   0.6894  
Slope       -0.006415   0.013688  -0.469   0.6393  
Aspect5     -0.354802   0.433453  -0.819   0.4130  
Aspect7     -0.519563   0.367129  -1.415   0.1570  
Aspect8     -0.374963   0.312013  -1.202   0.2295  
Soil4       -0.911459   0.375280  -2.429   0.0152 *
Soil6       -0.535102   0.707389  -0.756   0.4494  
CC2         -0.382547   0.378191  -1.012   0.3118  
CC3         -0.051661   0.308611  -0.167   0.8671  
CO          -0.095995   0.076460  -1.255   0.2093  
LC2          0.184564   0.371712   0.497   0.6195  
LC3         -0.172446   0.388932  -0.443   0.6575  
LC4          0.135938   0.406807   0.334   0.7383  
LC5          0.045341   0.583910   0.078   0.9381  
PA.sp        0.008536   0.019819   0.431   0.6667  
PA.other    -0.012056   0.006660  -1.810   0.0703 .
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for Negative Binomial(2.8717) family taken to be 1)

    Null deviance: 153.75  on 120  degrees of freedom
Residual deviance: 132.03  on 104  degrees of freedom
AIC: 374.27

Number of Fisher Scoring iterations: 1

              Theta:  2.87 
          Std. Err.:  1.50 

 2 x log-likelihood:  -338.266 </code></pre>
</div>
</div>
<p>From the above result, the intercept represents the estimated log count of the response variable (Gaenig) when all the predictor variables are zero, it is estimated to be -0.161328. The coefficient for Elevation is 0.004123. This means that for a one- unit increase in Elevtion, the log count of Gaenig is expected to increase by 0.0004123. The coefficient for Slope is -0.006415. This suggests that for a one-unit increase in Slope, the log coubt of Gaenig is expected to decrease by 0.006415. In the model, variable Soil4 is sinificant to Gaenig since the p-value is smaller than the significant level (0.05).</p>
<p>The null deviance is 153.75 and the Residual deviance is 132.03. A smaller residual deviance compared to the null deviance indicates that the model with predictor variables provides a better fit to the data compared to the null model. It quantifies the reduction in deviance achieved by including the predictor variables.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="co">#dispersion parameter</span></span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a>(disp.est <span class="ot">&lt;-</span> gaenig.nbf<span class="sc">$</span>deviance<span class="sc">/</span>gaenig.nbf<span class="sc">$</span>df.residual)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.269503</code></pre>
</div>
</div>
<p>For dispersion parameter is estimated to be 1.269503, this value suggests that there ay be overdispersion in the data, especially if it is significantly larger than 1.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="co">#chi-square test</span></span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>(gaenig.nbf, <span class="fu">cbind</span>(<span class="at">deviance =</span> deviance, <span class="at">df =</span> df.residual,</span>
<span id="cb61-3"><a href="#cb61-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">p =</span> <span class="fu">pchisq</span>(deviance, df.residual, <span class="at">lower.tail=</span><span class="cn">FALSE</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     deviance  df          p
[1,] 132.0283 104 0.03308387</code></pre>
</div>
</div>
<p>H0: Data not prefer full fitted model</p>
<p>H1: Data prefer the full fitted model</p>
<p>In the Chi-squared test, the p-value is 0.03308387, is smaller than the significant level (0.05), which support the H0, shows that the data not prefer the full fitted model,which suggests that the Negative Binomial Regression model is not significantly improves the fit over the null model. We can compare the deviance value (132.0283) with other model to see if it is the better fit model among others.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a>(an.nb <span class="ot">&lt;-</span> <span class="fu">anova</span>(gaenig.nbf, gaenig.nbn, <span class="at">test=</span><span class="st">"Chisq"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Likelihood ratio tests of Negative Binomial Models

Response: Gaenig
                                                                Model    theta
1                                                                   1 1.515638
2 Elevation + Slope + Aspect + Soil + CC + CO + LC + PA.sp + PA.other 2.871689
  Resid. df    2 x log-lik.   Test    df LR stat.   Pr(Chi)
1       120       -357.6281                                
2       104       -338.2662 1 vs 2    16 19.36198 0.2503397</code></pre>
</div>
</div>
<p>We can see that the p-value is 0.25, which larger than the significant level and suggested that the null negative binomial regression model is more better fit and better model.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="co">#deviance residuals</span></span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a>gaenig.nbf.res <span class="ot">&lt;-</span> <span class="fu">resid</span>(gaenig.nbf, <span class="at">type =</span> <span class="st">"deviance"</span>) </span>
<span id="cb65-3"><a href="#cb65-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(gaenig.nbf.res)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
-1.7398 -1.1679 -0.4000 -0.2853  0.4315  2.3940 </code></pre>
</div>
</div>
<p>The minimum deviance residual is -1.7398. This indicate that for some data points, the model overpredicts the response variable by a substantial amount. The 1st quartile value is -1.1679. This means that 25% of the data points have deviance residuals less than or equal to -1.1679. The median deviance residual is -0.4000, indicating that roughly half of the data points have deviance residuals less than -0.4000, and the other half have residuals greater than this value.</p>
<p>The mean deviance residual is -0.2853. On average, the model underpredicts the response variable by approximately 0.2853 units. The 3 rd quartile value is 0.4315. This means that 75% of the data points have deviance residuals less than or equal to 0.4315. The maximum deviance residual is 2.3940. This indicates that for some data points, the model underpredicts the response variable by a substantial amount.</p>
<p>We explore the model fit in more detail. We can fit a reduced model by dropping the predictor Elevation, slope, CC, CO, Aspect, LC, and PA.sp from thr null model, since the predictor Soil and PA.other have the smaller p-value than others.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a>gaenig.nbr <span class="ot">&lt;-</span> <span class="fu">glm.nb</span>(Gaenig<span class="sc">~</span>Soil<span class="sc">+</span>PA.other,<span class="at">data=</span>train.set)</span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(gaenig.nbr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm.nb(formula = Gaenig ~ Soil + PA.other, data = train.set, 
    init.theta = 1.930765404, link = log)

Coefficients:
             Estimate Std. Error z value Pr(&gt;|z|)   
(Intercept)  0.548735   0.173339   3.166  0.00155 **
Soil4       -0.616229   0.339388  -1.816  0.06941 . 
Soil6        0.232596   0.598710   0.388  0.69765   
PA.other    -0.016230   0.006488  -2.502  0.01236 * 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for Negative Binomial(1.9308) family taken to be 1)

    Null deviance: 138.96  on 120  degrees of freedom
Residual deviance: 128.99  on 117  degrees of freedom
AIC: 358.06

Number of Fisher Scoring iterations: 1

              Theta:  1.931 
          Std. Err.:  0.786 

 2 x log-likelihood:  -348.064 </code></pre>
</div>
</div>
<p>We can see that the AIC has reduced to 358.06, which become a better fit model. We can see that the intercept and PA.other are significant to the model since the p-value is smaller than the significant level. The residual deviance is smaller than the null deviance, prove than the model with the predictor variables provides a better git to the data compared to the null model.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>(gaenig.nbr, <span class="fu">cbind</span>(<span class="at">res.deviance =</span> deviance, <span class="at">df =</span> df.residual,<span class="at">p =</span> <span class="fu">pchisq</span>(deviance, df.residual, <span class="at">lower.tail=</span><span class="cn">FALSE</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     res.deviance  df         p
[1,]     128.9902 117 0.2113389</code></pre>
</div>
</div>
<p>The p-value is 0.2113389, which larger than the significant level (0.05), indicate than after dropping those predictor, the model is become more adequate. Since null model is more better fit, we will compare the null model with the reduced model.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a>(comp.nb <span class="ot">&lt;-</span> <span class="fu">anova</span>(gaenig.nbn, gaenig.nbr, <span class="at">test=</span><span class="st">"Chisq"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Likelihood ratio tests of Negative Binomial Models

Response: Gaenig
            Model    theta Resid. df    2 x log-lik.   Test    df LR stat.
1               1 1.515638       120       -357.6281                      
2 Soil + PA.other 1.930765       117       -348.0638 1 vs 2     3 9.564376
     Pr(Chi)
1           
2 0.02265628</code></pre>
</div>
</div>
<p>The null hypothesis (H0) assumes that there is no significant difference between the two models, and Model 1 is sufficient. The alternative hypothesis (H1) suggests that Model 2, which includes the “Soil” variable, is significantly better in terms of fit.</p>
<p>The p-value of 0.2210795 is greater than the significance level (0.05). Since the p-value is not less than 0.05, we fail to reject the null hypothesis. In other words, there is not enough evidence to suggest that reduced model provides a significantly better fit compared to null model. Therefore, null model is not significantly worse than reduced model, given the chi-squared test results.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Information criteria</span></span>
<span id="cb73-2"><a href="#cb73-2" aria-hidden="true" tabindex="-1"></a><span class="fu">AIC</span>(gaenig.nbr,gaenig.nbn)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>           df      AIC
gaenig.nbr  5 358.0638
gaenig.nbn  2 361.6281</code></pre>
</div>
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a><span class="fu">BIC</span>(gaenig.nbr,gaenig.nbn)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>           df      BIC
gaenig.nbr  5 372.0427
gaenig.nbn  2 367.2197</code></pre>
</div>
</div>
<p>For AIC, the model “gaenig.nbr” has an AIC of 358.0638, while “gaenig.nbn” has an AIC of 361.6281. For BIC, “gaenig.nbr” has a BIC of 372.0427, while “gaenig.nbn” has a BIC of 367.2197. Since we are prioritize model fit, we would choose the model with the lower AIC, which the reduced model is the better model. But overall, the AIC of reduced model and null model are similar.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a><span class="co">#in-sample mad on full fitted model</span></span>
<span id="cb77-2"><a href="#cb77-2" aria-hidden="true" tabindex="-1"></a>in_sample_mad_nbf <span class="ot">&lt;-</span> <span class="fu">mean</span>(<span class="fu">abs</span>(train.set<span class="sc">$</span>Gaenig <span class="sc">-</span> <span class="fu">predict</span>(gaenig.nbf, <span class="at">type =</span> <span class="st">"response"</span>)))</span>
<span id="cb77-3"><a href="#cb77-3" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">'In-sample MAD: '</span>, in_sample_mad_nbf)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>In-sample MAD:  0.9921456</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb79"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a><span class="co">#out-sample mad on full fitted model</span></span>
<span id="cb79-2"><a href="#cb79-2" aria-hidden="true" tabindex="-1"></a>out_sample_mad_nbf <span class="ot">&lt;-</span> <span class="fu">mean</span>(<span class="fu">abs</span>(test.set<span class="sc">$</span>Gaenig <span class="sc">-</span> <span class="fu">predict</span>(gaenig.nbf, <span class="at">newdata =</span> test.set, <span class="at">type =</span> <span class="st">"response"</span>)))</span>
<span id="cb79-3"><a href="#cb79-3" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">'Out-sample MAD: '</span>, out_sample_mad_nbf)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Out-sample MAD:  1.019177</code></pre>
</div>
</div>
<p>For the full fitted model, the in-sample MAD is approximately 0.9921456 and the out-of-sample MAD is approximately 1.019177.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb81"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1" aria-hidden="true" tabindex="-1"></a><span class="co">#in-sample mad on null model</span></span>
<span id="cb81-2"><a href="#cb81-2" aria-hidden="true" tabindex="-1"></a>in_sample_mad_nbn <span class="ot">&lt;-</span> <span class="fu">mean</span>(<span class="fu">abs</span>(train.set<span class="sc">$</span>Gaenig <span class="sc">-</span> <span class="fu">predict</span>(gaenig.nbn, <span class="at">type =</span> <span class="st">"response"</span>)))</span>
<span id="cb81-3"><a href="#cb81-3" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">'In-sample MAD: '</span>, in_sample_mad_nbn)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>In-sample MAD:  1.080117</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb83"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb83-1"><a href="#cb83-1" aria-hidden="true" tabindex="-1"></a><span class="co">#out-sample mad on  null model</span></span>
<span id="cb83-2"><a href="#cb83-2" aria-hidden="true" tabindex="-1"></a>out_sample_mad_nbn <span class="ot">&lt;-</span> <span class="fu">mean</span>(<span class="fu">abs</span>(test.set<span class="sc">$</span>Gaenig <span class="sc">-</span> <span class="fu">predict</span>(gaenig.nbn, <span class="at">newdata =</span> test.set, <span class="at">type =</span> <span class="st">"response"</span>)))</span>
<span id="cb83-3"><a href="#cb83-3" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">'Out-sample MAD: '</span>, out_sample_mad_nbn)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Out-sample MAD:  0.9126722</code></pre>
</div>
</div>
<p>For the null model, the in-sample MAD is approximately 1.080117 and the out-of-sample MAD is approximately 0.9126722.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb85"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb85-1"><a href="#cb85-1" aria-hidden="true" tabindex="-1"></a><span class="co">#in-sample mad on reduced model</span></span>
<span id="cb85-2"><a href="#cb85-2" aria-hidden="true" tabindex="-1"></a>in_sample_mad_nbr <span class="ot">&lt;-</span> <span class="fu">mean</span>(<span class="fu">abs</span>(train.set<span class="sc">$</span>Gaenig <span class="sc">-</span> <span class="fu">predict</span>(gaenig.nbr, <span class="at">type =</span> <span class="st">"response"</span>)))</span>
<span id="cb85-3"><a href="#cb85-3" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">'In-sample MAD: '</span>, in_sample_mad_nbr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>In-sample MAD:  1.056339</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb87"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb87-1"><a href="#cb87-1" aria-hidden="true" tabindex="-1"></a><span class="co">#out-sample mad on reduced model</span></span>
<span id="cb87-2"><a href="#cb87-2" aria-hidden="true" tabindex="-1"></a>out_sample_mad_nbr <span class="ot">&lt;-</span> <span class="fu">mean</span>(<span class="fu">abs</span>(test.set<span class="sc">$</span>Gaenig <span class="sc">-</span> <span class="fu">predict</span>(gaenig.nbr, <span class="at">newdata =</span> test.set, <span class="at">type =</span> <span class="st">"response"</span>)))</span>
<span id="cb87-3"><a href="#cb87-3" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">'Out-sample MAD: '</span>, out_sample_mad_nbr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Out-sample MAD:  0.9585369</code></pre>
</div>
</div>
<p>For the null model, the in-sample MAD is approximately 1.056339 and the out-of-sample MAD is approximately 0.9585369</p>
<p>From the result of in-sample MAD and out-sample MAD, we can see that both of them have the same result, For in-sample MAD, both full fitted model are 1.080117. For out-sample MAD, both fitted model are 0.9127.</p>
<p>In this case, I would suggest the Negative Binomial model because it is with a lower dispersion parameter, accounts for overdispersion, and relatively low AIC values which have the goodness of fit and model complexity. In the several model of negative binomial regression model, I would prefer the null model of negative binomial regression model because the AIC is lower than the reduced model. Moreover, the out-sample MAD of null model is lower than that of others negative binomial regression model. It suggests that the null model’s predictions are more accurate and have better generalization performance when applied to new, unseen data. For null negative binomial model, there is no any predictor that use for predictions but provide a better fit. It might because the full fitted model may be overly complex and may overfit the training data. Also there might be capture spurious or random correlations between predictors and the response variable.s</p>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>